# Generated by Django 3.2.4 on 2021-06-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_logo',
        ),
    ]
