# Generated by Django 3.2.4 on 2021-06-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_logo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
