# Generated by Django 3.2.4 on 2021-06-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_movie_movie_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
