# Generated by Django 3.2.4 on 2021-06-28 16:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0006_alter_movie_movie_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title']},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'movie', 'rating')},
        ),
    ]
